version: 30
jobs:
- name: Deploy FreeIPA on KVM
  steps:
  - !CommandStep
    name: Clone freeipa-workshop-deployer
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: "if [ ! -d /opt/freeipa-workshop-deployer ];\nthen \n  cd /opt/\n  git clone https://github.com/tosin2013/freeipa-workshop-deployer.git\n  cd freeipa-workshop-deployer\nelse\n  cd /opt/freeipa-workshop-deployer\n  git config pull.rebase false\n  git pull\nfi\n"
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !TextParam
    name: VM_HOSTNAME
    allowEmpty: false
    multiline: false
    defaultValueProvider: !SpecifiedDefaultValue
      value: vm_name
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
